### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] Unexpected token ';'

### ISSUE THREAD

**Issue by PeWe79** [gAlleb/nuxt-om#2]
After update `Pinia 2.3.0` and `@pinia/nuxt 0.9.0` got error `[nuxt] [request error] [unhandled] [500] Unexpected token ';'`.
I think the problem coming from `Menu` and `MenuButton`thats actualy from `@headlessui/vue`.

**Comment by gAlleb** [comment]
Yeah, it's their new bug. It effects only `dev` mode. Builds work fine. 

https://github.com/nuxt/ui/issues/2971
https://github.com/vitejs/vite/issues/19096

(Also old issue https://github.com/vuejs/pinia/issues/2725)

However builds work fine. We can wait for the fix or downgrade Vite to 5. I think they'll fix it soon - https://github.com/vitejs/vite/issues/19096

**Comment by gAlleb** [comment]
yes, adding 

```
  "overrides": {
    "vue": "latest",
    "@parcel/watcher": "2.1.0",
    "vite": "5.4.11"
  },
```

to package.json fixes it. However sometimes throws a warning or an error:

```
Pre-transform error: Failed to resolve import "#app-manifest" from "node_modules/nuxt/dist/app/composables/manifest.js?v=6d140795". Does the file exist? 
```
So i would wait a little bit.

**Comment by PeWe79** [comment]
Yes, it works.
